import type { GenerationTask } from "./types";

const now = Date.now();
const minutesAgo = (minutes: number) => now - minutes * 60_000;

export const generationTaskSeed: GenerationTask[] = [
  {
    id: "task-video-1",
    type: "video",
    status: "running",
    prompt:
      "Кинематографичный облет стеклянной башни ERA2 на закате, теплый свет, плавная камера",
    modelName: "Kling 2.5 Turbo",
    credits: 75,
    createdAt: minutesAgo(18),
    updatedAt: minutesAgo(1),
    progress: 46,
    etaSeconds: 78,
    durationSeconds: 8,
  },
  {
    id: "task-image-1",
    type: "image",
    status: "running",
    prompt:
      "Постер продукта в стиле warm coal: оранжевое свечение, минималистичная типографика",
    modelName: "Nano Banana",
    credits: 30,
    createdAt: minutesAgo(12),
    updatedAt: minutesAgo(1),
    progress: 68,
    etaSeconds: 24,
  },
  {
    id: "task-text-1",
    type: "text",
    status: "queued",
    prompt:
      "Сформулируй пять вариантов короткого оффера для страницы подписки на AI-модели",
    modelName: "GPT-4o",
    credits: 5,
    createdAt: minutesAgo(9),
    updatedAt: minutesAgo(9),
    progress: 0,
    etaSeconds: 38,
    queuePosition: 1,
  },
  {
    id: "task-audio-1",
    type: "audio",
    status: "queued",
    prompt:
      "Голосовое интро для подкаста про нейросети, спокойный мужской голос, 20 секунд",
    modelName: "ElevenLabs v3",
    credits: 40,
    createdAt: minutesAgo(8),
    updatedAt: minutesAgo(8),
    progress: 0,
    etaSeconds: 112,
    durationSeconds: 20,
    queuePosition: 2,
  },
  {
    id: "task-video-2",
    type: "video",
    status: "queued",
    prompt:
      "Макро-видео: капля чернил растворяется в воде, медленное движение, темный фон",
    modelName: "Veo 3",
    credits: 120,
    createdAt: minutesAgo(7),
    updatedAt: minutesAgo(7),
    progress: 0,
    etaSeconds: 146,
    durationSeconds: 10,
    queuePosition: 3,
  },
  {
    id: "task-image-2",
    type: "image",
    status: "done",
    prompt:
      "Иконка ассистента для раздела дизайн-студии, плоская форма, оранжевый акцент",
    modelName: "Flux 1.1 Pro",
    credits: 25,
    createdAt: minutesAgo(45),
    updatedAt: minutesAgo(31),
    progress: 100,
    etaSeconds: 0,
    resultLabel: "PNG готов",
  },
  {
    id: "task-text-2",
    type: "text",
    status: "done",
    prompt: "Напиши дружелюбное уведомление о завершении пакетной генерации",
    modelName: "Claude Sonnet 4.5",
    credits: 8,
    createdAt: minutesAgo(55),
    updatedAt: minutesAgo(44),
    progress: 100,
    etaSeconds: 0,
    resultLabel: "Текст готов",
  },
  {
    id: "task-audio-2",
    type: "audio",
    status: "failed",
    prompt: "Lo-Fi бит для работы с мягкими клавишами и виниловым шумом",
    modelName: "Suno v4",
    credits: 60,
    createdAt: minutesAgo(33),
    updatedAt: minutesAgo(22),
    progress: 37,
    etaSeconds: 0,
    durationSeconds: 180,
    error: "Модель временно недоступна",
  },
  {
    id: "task-image-3",
    type: "image",
    status: "canceled",
    prompt: "Футуристичный баннер для раздела видео, стекло и медь, без текста",
    modelName: "Midjourney v7",
    credits: 45,
    createdAt: minutesAgo(66),
    updatedAt: minutesAgo(58),
    progress: 14,
    etaSeconds: 0,
  },
  {
    id: "task-text-3",
    type: "text",
    status: "queued",
    prompt: "Сравни GPT, Claude и Gemini для задач UX-исследований в одной таблице",
    modelName: "Gemini 2.5 Pro",
    credits: 6,
    createdAt: minutesAgo(5),
    updatedAt: minutesAgo(5),
    progress: 0,
    etaSeconds: 42,
    queuePosition: 4,
  },
];
